/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coba;

import java.awt.Color;

/**
 *
 * @author lenovo
 */
public class testText extends javax.swing.JFrame {

    /**
     * Creates new form testText
     */
    public testText() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
        //txt.addItemSuggestion("Java Swing");
        //txt.addItemSuggestion("Java Programming");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new textfield_suggestion.TextFieldSuggestion();
        textFieldSuggestion2 = new textfield_suggestion.TextFieldSuggestion();
        textField1 = new textfield.TextField();
        passwordField2 = new textfield.PasswordField();
        passwordField1 = new textfield.PasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt.setText("textFieldSuggestion1");
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 69, -1, -1));

        textFieldSuggestion2.setText("textFieldSuggestion2");
        getContentPane().add(textFieldSuggestion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 127, -1, -1));

        textField1.setLabelText("Username");
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 343, -1));

        passwordField2.setLabelText("Password");
        passwordField2.setShowAndHide(true);
        getContentPane().add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 340, -1));

        passwordField1.setText("passwordField1");
        getContentPane().add(passwordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testText().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private textfield.PasswordField passwordField1;
    private textfield.PasswordField passwordField2;
    private textfield.TextField textField1;
    private textfield_suggestion.TextFieldSuggestion textFieldSuggestion2;
    private textfield_suggestion.TextFieldSuggestion txt;
    // End of variables declaration//GEN-END:variables
}
