/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sriknd;

import custom.notif;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class login extends javax.swing.JFrame {
    int attempt=1;
    koneksi k=new koneksi();

    /**
     * Creates new form NewJFrame
     */
    public login() {
        initComponents();
        k.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubahpass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tusername = new textfield.TextField();
        tpass = new textfield.PasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ubahpass.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        ubahpass.setText("Ubah Password");
        ubahpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahpassMouseClicked(evt);
            }
        });
        getContentPane().add(ubahpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 640, 150, 29));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\back\\Group 6.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 720, 250, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\back\\Group 5.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 720, -1, -1));

        tusername.setBackground(new java.awt.Color(229, 229, 229));
        tusername.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tusername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tusernameFocusGained(evt);
            }
        });
        getContentPane().add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 402, 600, 80));

        tpass.setBackground(new java.awt.Color(229, 229, 229));
        tpass.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tpass.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tpass.setShowAndHide(true);
        getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, 600, 80));

        jLabel1.setBackground(new java.awt.Color(240, 180, 107));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\back\\Login.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1943, 1053);
    }// </editor-fold>//GEN-END:initComponents

    private void ubahpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahpassMouseClicked
        new ubahpasswoard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ubahpassMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setergeter1.setIdUser(String.valueOf(tusername.getText()));
        if(attempt<3) {
        try {
            Connection con=k.getcon();
            String sql="SELECT * FROM karyawan WHERE id_user='"+tusername.getText()
            +"' AND password='"+tpass.getText()+"'";
            PreparedStatement ps=con.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            if (rs.next()) {
                if(tusername.getText().equals(rs.getString("id_user"))
                    && tpass.getText().equals(rs.getString("password"))
                        && rs.getString("akses").equals("Admin")) {
                    notif obj = new notif(this);
                    obj.showMessage("Message Dialog", "Berhasil Login Sebagai Admin");
                    if (obj.getMessageType() == notif.MessageType.OK) {
                        System.out.println("User click ya");
                        this.setVisible(false);
                        new admin().setVisible(true);
                        this.dispose();
                    } else {
                        System.out.println("User click batal");
                        //new login().setVisible(true);
                    }
                } else if (tusername.getText().equals(rs.getString("id_user"))
                    && tpass.getText().equals(rs.getString("password"))
                        && rs.getString("akses").equals("Kasir")) {
                    notif obj = new notif(this);
                    obj.showMessage("Message Dialog", "Berhasil Login Sebagai Kasir");
                    if (obj.getMessageType() == notif.MessageType.OK) {
                        System.out.println("User click ya");
                        this.setVisible(false);
                        new kasir().setVisible(true);
                        this.dispose();
                    } else {
                        System.out.println("User click batal");
                }
                }
            } else {
                notif obj = new notif(this);
                obj.showMessage("Peringatan", "Username atau Password Salah"+attempt);
                if (obj.getMessageType() == notif.MessageType.OK) {
                    System.out.println("User click ya");
                } else {
                    System.out.println("User click batal");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }else if(attempt==3){
                notif obj = new notif(this);
                obj.showMessage("Peringatan", "Kesempatan Telah Habis! Silahkan Ubah Password");
                if (obj.getMessageType() == notif.MessageType.OK) {
                    System.out.println("User click ya");
                    this.dispose();
                    this.setVisible(false);
                    new ubahpasswoard().setVisible(true);
                } else {
                    System.out.println("User click batal");
                }
            }
        attempt++;
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new opening().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tusernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tusernameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private textfield.PasswordField tpass;
    private textfield.TextField tusername;
    private javax.swing.JLabel ubahpass;
    // End of variables declaration//GEN-END:variables
}
