/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sriknd;

import custom.notif;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class ubahpasswoard extends javax.swing.JFrame {
    koneksi k=new koneksi();
    /**
     * Creates new form ubahpasswoard
     */
    public ubahpasswoard() {
        initComponents();
        k.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info = new javax.swing.JLabel();
        ubahh = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tuser = new textfield.TextField();
        tpasswoard = new textfield.PasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        info.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 630, 600, 50));

        ubahh.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        ubahh.setForeground(new java.awt.Color(255, 255, 255));
        ubahh.setIcon(new javax.swing.ImageIcon("D:\\back\\Group 6 (1).png")); // NOI18N
        ubahh.setFocusable(false);
        ubahh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ubahh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahhMouseClicked(evt);
            }
        });
        getContentPane().add(ubahh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 730, -1, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\back\\Group 5.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 730, -1, -1));

        tuser.setBackground(new java.awt.Color(229, 229, 229));
        tuser.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tuser.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tuserFocusGained(evt);
            }
        });
        getContentPane().add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 402, 600, 80));

        tpasswoard.setBackground(new java.awt.Color(229, 229, 229));
        tpasswoard.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tpasswoard.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tpasswoard.setShowAndHide(true);
        tpasswoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpasswoardMouseClicked(evt);
            }
        });
        tpasswoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswoardActionPerformed(evt);
            }
        });
        getContentPane().add(tpasswoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, 600, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\back\\Ubah Password.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1960, 1000));

        setBounds(0, 0, 1949, 1084);
    }// </editor-fold>//GEN-END:initComponents

    private void ubahhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahhMouseClicked
        if (tpasswoard.getText().trim().length()>8 ) {
            info.setText("Password harus 8 karakter");
            info.setVisible(true);
        }else if (tpasswoard.getText().trim().length()<8 ){
            info.setText("Password harus 8 karakter");
            info.setVisible(true);
        } else {
            info.setVisible(false);
        try {
        Connection c=k.getcon();
        String sql="update karyawan set password='"+tpasswoard.getText()+"' where id_user='"+tuser.getText()+"'";
        PreparedStatement ps=c.prepareStatement(sql);
        ps.execute();
                notif obj = new notif(this);
                obj.showMessage("Peringatan", "Password Berhasil Diubah");
                if (obj.getMessageType() == notif.MessageType.OK) {
                    System.out.println("User click ya");
                    this.dispose();
                    new login().setVisible(true);
                } else {
                    System.out.println("User click batal");
                }
        //JOptionPane.showMessageDialog(null, "Passwoard berhasil diubah");
        tuser.setText("");
        tpasswoard.setText("");
       } catch (Exception e){
           //JOptionPane.showMessageDialog(null, e.getMessage());
       }
       }
    }//GEN-LAST:event_ubahhMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tuserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserFocusGained

    private void tpasswoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswoardActionPerformed
        if (tpasswoard.getText().trim().length()>8) {
            info.setText("Password harus 8 karakter");
            info.setVisible(true);
        }else if (tpasswoard.getText().trim().length()<8 ){
            info.setText("Password harus 8 karakter");
            info.setVisible(true);
        } else {
            info.setVisible(false);
        }
    }//GEN-LAST:event_tpasswoardActionPerformed

    private void tpasswoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpasswoardMouseClicked
        if (tpasswoard.getText().trim().length()>8 && tpasswoard.getText().trim().length()<8) {
            info.setText("Password harus 8 karakter");
            info.setVisible(true);
        } else {
            info.setVisible(false);
        }
    }//GEN-LAST:event_tpasswoardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubahpasswoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubahpasswoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubahpasswoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubahpasswoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubahpasswoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private textfield.PasswordField tpasswoard;
    private textfield.TextField tuser;
    private javax.swing.JLabel ubahh;
    // End of variables declaration//GEN-END:variables
}
